version: '3.7'
services: 
  web:
    container_name: "react"
    build: ./frontend
    command: "yarn start"
    volumes: 
      - ./frontend:/frontend
      - node_module_volumes:/frontend/node_modules
    ports:
      - 3000:3000
    environment: 
      - CHOKIDAR_USEPOLLING=true
  
  api:
    container_name: "django"
    build: ./api
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes: 
      - ./api:/api
    ports:
      - 8000:8000

volumes: 
  node_module_volumes: